FROM node:16.13

WORKDIR /app

ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

RUN npm install -g npm

COPY package.json package-lock.json ./

RUN npm install

COPY . ./

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
