version: '3.2'
services:
  nest:
    container_name: nest 
    build:
      context: ./
      dockerfile: 'Dockerfile.dev'
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - kafka    
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
      - 29092:29092
    volumes:
      - 'kafka_data:/bitnami' 
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    hostname: kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local