version: '3.2'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    logging:
      driver: "none"
    container_name: zookeeper2
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    logging:
      driver: "none"
    container_name: kafka2
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    hostname: 'kafka-internal.io'
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka-internal.io
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local